server.port=8443

spring.jpa.hibernate.ddl-auto = none

# 错误信息（调试用）
server.error.include-message=always

# MyBatis 配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.evan.entity
mybatis.configuration.map-underscore-to-camel-case=true

# 数据库连接信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/luckyblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=rootroot

# Redis 连接信息
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# JWT 配置
token.secretKey=naccl-blog-jwt-secret-key-2024
token.expireTime=2592000000
